import 'package:flutter/material.dart';

import 'model.dart';

List<Q_Bank> question = <Q_Bank>[
  Q_Bank(
    id: 1,
    title: "Which of the following has no Skeleton at all?",
    o1: "A) Star fish",
    o2: "B) Sponge",
    o3: "C) Jelly fish",
    o4: "D) Gold fish",
    ans: "C",
    mycolor: Colors.deepPurpleAccent,
  ),
  Q_Bank(
    id: 2,
    title: "Which place is known as the roof of the world?",
    o1: "A) Tibet",
    o2: "B) Himalayan",
    o3: "C) Nepal",
    o4: "D) China",
    ans: "A",
    mycolor: Colors.blueAccent,
  ),
  Q_Bank(
    id: 3,
    title: "Which is the densest jungle in the world?",
    o1: "A) Africas\n     jungle",
    o2: "B) The Amazon\n     rainforest",
    o3: "C) Gir forest",
    o4: "D) Sundarbuns\n     forest",
    ans: "B",
    mycolor: Colors.cyanAccent,
  ),
  Q_Bank(
    id: 4,
    title: "Which country is called the land of rising sun?",
    o1: "A) Canada",
    o2: "B) Russia",
    o3: "C) America",
    o4: "D) Japan",
    ans: "D",
    mycolor: Colors.pinkAccent,
  ),
  Q_Bank(
    id: 5,
    title: "Which is the most sensitive organ in our body?",
    o1: "A) Skin",
    o2: "B) Ear",
    o3: "C) Eyes",
    o4: "D) Nose",
    ans: "A",
    mycolor: Colors.lightBlue,
  ),
  Q_Bank(
    id: 6,
    title: "What type of tree do dates grow on?",
    o1: "A) Coconut",
    o2: "B) Pine",
    o3: "C) Palm",
    o4: "D) Birch",
    ans: "C",
    mycolor: Colors.redAccent,
  ),
  Q_Bank(
    id: 7,
    title: "Can you name the country from where Parmesan cheese comes?",
    o1: "A) India",
    o2: "B) China",
    o3: "C) Italy",
    o4: "D) France",
    ans: "C",
    mycolor: Colors.greenAccent,
  ),
  Q_Bank(
    id: 8,
    title: "‘Stars and Stripes’ is the nickname of the flag of which country?",
    o1: "A) America",
    o2: "B) Turkey",
    o3: "C) Greece",
    o4: "D) Switzerland",
    ans: "A",
    mycolor: Colors.deepOrange,
  ),
  Q_Bank(
    id: 9,
    title: "Which is the tallest waterfall in the world?",
    o1: "A) Niagara\n     Falls",
    o2: "B) Denmark\n     Strait",
    o3: "C) Angel falls",
    o4: "D) Three\n     Sisters Falls",
    ans: "B",
    mycolor: Colors.tealAccent,
  ),
  Q_Bank(
    id: 10,
    title: "Which gas is most abundant in the earth’s atmosphere?",
    o1: "A) Oxygen",
    o2: "B) Ozone",
    o3: "C) Nitrogen",
    o4: "D) Carbon\n     Dioxide",
    ans: "C",
    mycolor: Colors.lightBlueAccent,
  ),
];
